# Generated by Django 3.0.5 on 2020-05-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-create_date',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
