# Generated by Django 3.0.5 on 2020-05-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200515_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='dsf?', help_text='Post Image', upload_to='posts', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
